version: '3'
services:
    gateway:
        build: .
        ports:
            - "3000:3000"
        command: node dist/www.js
        environment:
            - DEBUG=fluid:*
            - NODE_ENV=development
            - login__microsoft__clientId
            - login__microsoft__secret
            - login__accounts
        restart: always
    gitrest:
        image: mcr.microsoft.com/fluidframework/routerlicious/gitrest:latest
        restart: always
    redis:
        image: redis:alpine
    mongodb:
        image: mongo:3.4.3
    riddler:
        image: mcr.microsoft.com/fluidframework/routerlicious/server:latest
        command: node dist/riddler/www.js
        environment:
            - DEBUG=routerlicious:*
        restart: always
